version: 0.0
Resources:
  - HelloWorld:
      Type: AWS::Lambda::Function
      Properties:
        Name: "ExternalApiCallerLambda"
        Alias: "dev"
        CurrentVersion: "$CurrentVersion"
        TargetVersion: "$TargetVersion"