version: 0.2

phases:
  build:
    commands:
      - CurrentVersion=$(aws lambda get-alias --function-name ExternalApiCallerLambda --name dev --query 'FunctionVersion' --output text)
      - echo CurrentVersion=$CurrentVersion
      - aws lambda publish-version --function-name ExternalApiCallerLambda
      - TargetVersion=$(aws lambda list-versions-by-function --function-name ExternalApiCallerLambda --query 'Versions[-1].Version' --output text)
      - echo TargetVersion=$TargetVersion
      - sed -i -e "s/{{CurrentVersion}}/$CurrentVersion/g" appspec.yml
      - sed -i -e "s/{{TargetVersion}}/$TargetVersion/g" appspec.yml
    
artifacts:
  files:
    - "appspec.yml"
    - "**/*"